# Generated by Django 3.0 on 2022-11-20 07:30

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=255)),
                ('hid', models.CharField(max_length=255)),
                ('web', models.URLField(max_length=255)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('DirName', models.CharField(max_length=255)),
                ('DirContact', models.CharField(max_length=255)),
                ('DirEmail', models.EmailField(max_length=255)),
                ('License', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20)),
                ('CertNumber', models.CharField(max_length=255)),
                ('LicDate', models.DateField()),
                ('Photo', models.ImageField(upload_to='hospital')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=20)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.District')),
            ],
        ),
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('staffid', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=20)),
                ('hname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('fname', models.CharField(max_length=255)),
                ('mname', models.CharField(max_length=255)),
                ('aadhar', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='donor')),
                ('aadhar_doc', models.FileField(upload_to='aadhar')),
                ('password', models.CharField(max_length=20)),
                ('bloodgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.BloodGroup')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.District')),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Organ')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.State')),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.State'),
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('fname', models.CharField(max_length=255)),
                ('mname', models.CharField(max_length=255)),
                ('organ', multiselectfield.db.fields.MultiSelectField(choices=[('Liver', 'Liver'), ('Heart', 'Heart'), ('Kidney', 'Kidney'), ('Lungs', 'Lungs'), ('Pancreas', 'Pancreas'), ('Small Intestine', 'Small Intestine'), ('Corneas', 'Corneas'), ('Heart Valves', 'Heart Valves'), ('Skin', 'Skin')], max_length=75)),
                ('aadhar', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='donor')),
                ('aadhar_doc', models.FileField(upload_to='aadhar')),
                ('password', models.CharField(max_length=20)),
                ('bloodgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.BloodGroup')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.District')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.State')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.State'),
        ),
        migrations.CreateModel(
            name='BrainDeath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('organ', multiselectfield.db.fields.MultiSelectField(choices=[('Liver', 'Liver'), ('Heart', 'Heart'), ('Kidney', 'Kidney'), ('Lungs', 'Lungs'), ('Pancreas', 'Pancreas'), ('Small Intestine', 'Small Intestine'), ('Corneas', 'Corneas'), ('Heart Valves', 'Heart Valves'), ('Skin', 'Skin')], max_length=75)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20)),
                ('address', models.TextField()),
                ('consent_form', models.FileField(upload_to='consent_form')),
                ('bloodgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.BloodGroup')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.District')),
                ('hname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Hospital')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.State')),
            ],
        ),
    ]
